project:
  type: book
  output-dir: docs/_book

book:
  title: "BioStatistics"
  author: "William Hagedorn-Rasmussen"
  date: "02/02/2024"
  chapters:
    - index.qmd
    
    - part: tidy00.qmd
      chapters: 
        - tidy01.qmd
        - tidy02.qmd
        - tidy03.qmd
        
    - part: stat00.qmd
      chapters:
        - stat01.qmd
        - stat02.qmd
        - stat03.qmd
        
        
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: TRUE
    toc-depth: 4
    toc-expand: 4
    theme: cosmo

editor: source

