project:
  type: book

book:
  title: "BioStatistics"
  author: "William Hagedorn-Rasmussen"
  date: "02/02/2024"
  chapters:
    - index.qmd
    
    - part: tidy00.qmd
      chapters: 
        - tidy01.qmd
        
    - part: stat00.qmd
      chapters:
        - stat01.qmd
        
        
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: source

