project:
  type: book
  output-dir: docs/_book

book:
  title: "BioStatistics"
  author: "William Hagedorn-Rasmussen"
  date: "02/02/2024"
  chapters:
    - index.qmd
    
    - part: tidy00_book_intro.qmd
      chapters: 
        - tidy01_intro_package.qmd
        - tidy02_mult_models.qmd
        - tidy03_hyperparam.qmd
        
    - part: stat00_intro.qmd
      chapters:
        - stat01_diversity.qmd
        - stat02_wilcoxon.qmd
        - stat03_mult_testing.qmd
        - stat04_OLS.qmd
        - stat05_log_reg.qmd
        - stat06_enet.qmd
        - stat07_bias_var.qmd
        
    - part: pre00_intro.qmd
      chapters:
        - pre01_pca.qmd
        - pre02_pls.qmd
        - pre03_umap.qmd
        
    - part: apply00_intro.qmd
      chapters:
        - apply01_model_data.qmd
        
        
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: TRUE
    toc-depth: 4
    toc-expand: 4
    theme: cosmo

editor: source

