Set seed and load packages.
```{r}
#| output: FALSE
#| code-fold: true
#| code-summary: "Show the code"

set.seed(1337)

library("tidymodels")
tidymodels::tidymodels_prefer()
library("mdatools")
```

Load data.
```{r}
#| output: FALSE
#| code-fold: true
#| code-summary: "Show the code"

count_matrix_clr <- readr::read_rds("https://github.com/WilliamH-R/BioStatistics/raw/main/data/count_matrix/count_matrix_clr.rds") |> 
  select(-"NA")

meta <- read.csv(file = "data/metadata.txt") |> 
  as_tibble() |>
  select(Run, chem_administration, ETHNICITY, geo_loc_name,
         Host_age, host_body_mass_index, Host_disease, host_phenotype, host_sex) |> 
  rename(Sample = Run,
         Treatment = chem_administration,
         Ethnicity = ETHNICITY,
         Location = geo_loc_name,
         Age = Host_age,
         BMI = host_body_mass_index,
         Disease_severity = Host_disease,
         EDSS = host_phenotype,
         Sex = host_sex) |>
  mutate(Patient_status = case_when(Disease_severity == "1HealthyControl" ~ "Healthy",
                                    TRUE ~ "MS"),
         #Patient_status = as.factor(Patient_status),
         EDSS = as.factor(EDSS),
         EDSS = case_when(is.na(EDSS) & Disease_severity == "1HealthyControl" ~ "-1",
                          is.na(EDSS) & Disease_severity != "1HealthyControl" ~ "Unknown",
                          TRUE ~ EDSS),
         EDSS = as.factor(EDSS))
```

# Partial Least Squares

```{r}
count_w_meta <- count_matrix_clr |>
  left_join(meta |> select(Sample, Patient_status),
            by = "Sample") |>
  select(-Sample)

pls <- plsr(Patient_status ~ Actinomyces + Adlercreutzia + Agathobacter + Akkermansia + Alistipes,
            ncomp = 2,
            data = count_w_meta,
            scale = FALSE,
            validation = "CV")
```

```{r}
plsda <- mdatools::plsda(x = count_w_meta |> select(-Patient_status),
                         c = count_w_meta |> pull(Patient_status),
                         scale = FALSE,
                         cv = 1)
```


```{r}
summary(plsda)
```



## Reading stuff
https://recipes.tidymodels.org/reference/step_pls.html (set outcome to "class" it seems)
http://www2.imm.dtu.dk/courses/27411/doc/Lection05/PLShandouts.pdf
https://www.youtube.com/results?search_query=partial+least+squares