```{r setup, include = FALSE}
set.seed(1337)

library("tidymodels")
tidymodels::tidymodels_prefer()

mtcars <- mtcars |> 
  as_tibble()
```

# Logistic Regression
Predict TRUE or FALSE, not a continuous value. The output is a probability from 0 to 1.

OLS uses sum of squared residuals (SSR). Logistic regression uses maximum likelihood.

Maximum likelihood: Imagine a range of data and we want to fit a normal distribution. We want to find the mean and standard deviation that maximizes the likelihood of the data. Maximizing likelihood here means, the highest chance of observing the range of data we got if we assume it follow the particular normal distribution we are testing. Say the true mean of our data was 10, but we tested a normal distribution centered around 0, the likelihood of observing the data with mean 10 is very low. We do the same thing for the standard deviation.

The y-axis for logistic regression goes from 0 to 1 reflecting the probability of the class measured along the y-axis. This can be transformed into a more standard y-axis på taking the log of the odds ratio. The log-odds ratio is the logit function, $log(p)=log10(p/1-p)$. For example, 0.5 probability is 0 log-odds ratio, the center on the transformed y-axis. 0.731 probability is 1 log-odds ratio and 0.88 probability is 2 log-odds ratio, 0.95 probability is 3 log-odds ratio.

The points that were classified as TRUE, i.e. 1 on the previous y-axis, is transformed to positive infinity on the new y-axis as $log10(1/1-1)=log10(1/0)=log10(1)-log10(0)$, which is positive infinity. The points that were classified as FALSE, i.e. 0 on the previous y-axis, is transformed to negative infinity on the new y-axis as $log10(0/1-0)=log10(0/1)=log10(0)-log10(1)$, which is negative infinity. So, the interval of 0.5 to 1 on the old axis as been transformed into an interval from 0 to positive infinity and vice versa.

The logit function transform the sigmoid function into a straight line with the log-odds y-axis. Cannot use least squares to find the best fit line as data points are pushed to positive and negative infinity, and as such the residuals are also infinity. Instead, we use maximum likelihood to find the best fit line. Project the data points onto a candidate logit function, this gives each data point a candidate log(odds) value, not just negative or positive infinity. From candidate log(odds) calculate back into probability with the inverse logit function, $p = \frac{e^{log10(p)}}{1 + e^{log10(p)}}$. The data not exist in the old space with a y-axis from 0 to 1. For the TRUE class, note their y-values and multiply them all (y-value is equal to their probability of being true). For the FALSE class, note their y-values and subtract them all from 1 (y-value is equal to their probability of being in the TRUE class, but we want the probability of being the in the FALSE). These probabilities are also multiplied, afterwards multiply the two resulting products to get a final product. For some reason, people tend to take the log of the probabilities and sum them instead of multiplying, which is the log-likelihood. The log-likelihood is maximized when the model is fit to the data. This is done by trying a new candidate line, get candidate log(odds) values and repeat the above process. The candidate line that maximizes (highest value) the log-likelihood is the best fit line.


https://www.youtube.com/watch?v=vN5cNN2-HWE
https://www.youtube.com/watch?v=BfKanl1aSG0
https://www.youtube.com/watch?v=xxFYro8QuXA